package dev.olaxomi.backend.enums;

public enum ActionType {
    CREATE_USER,
    VIEW_USER,
    UPDATE_USER,
    DELETE_USER,
    CREATE_CUSTOMER,
    VIEW_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    CREATE_PRODUCT,
    VIEW_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    CREATE_TRANSACTION,
    VIEW_TRANSACTION,
    UPDATE_TRANSACTION,
    DELETE_TRANSACTION,
    VIEW_WALLET,
    UPDATE_WALLET
}
